export const strings = {
  common: {
    back: '← Назад',
    close: 'Закрити',
  },
  onboarding: {
    eyebrow: 'SNAPSY',
    promiseTitle: 'Без банку.\nБез карток.\n',
    promiseTitleAccent: 'Тільки фото.',
    promiseSub:
      'Сфотографуй чек, скріншот або перешли лист — ми самі розберемось, скільки й коли ти платиш.',
    start: 'Почати',
    haveAccount: 'Вже маю акаунт',
    trust1: 'Розпізнавання — прямо на пристрої',
    trust2: 'Жодного доступу до банку чи пошти',
    trust3: 'Працює без реєстрації',
    stepLabel: 'Крок 1 з 2',
    scanTitle: 'Один скріншот — кілька підписок',
    scanSub:
      'Найшвидший спосіб наповнити список: екран, де і так зберігаються всі твої підписки через App Store.',
    step1: 'Відкрий Налаштування → Підписки',
    step2: 'Зроби скріншот цього екрана',
    step3: 'Повернись сюди — решту зробимо ми',
    exampleLabel: 'Приклад екрана',
    exampleTitle: 'Підписки',
    chooseScreenshot: 'Обрати скріншот',
    skip: 'Пропустити цей крок',
    resultTitle: 'Знайдено 9 підписок',
    resultSub: '≈ 41 760 ₴ на рік',
    foundListLabel: 'Знайдено зі скріншота',
    continue: 'Продовжити',
    continueNote: 'Можна відредагувати будь-яку картку пізніше',
  },
  home: {
    eyebrow: 'ОГЛЯД',
    title: 'Твої підписки',
    thisMonth: 'Цього місяця',
    timelineTitle: 'Хронологія списань',
    timelineLink: '9 усього',
  },
  settings: {
    title: 'Налаштування',
    proTitle: 'Перейти на Snapsy Pro',
    proSub: 'Безліміт підписок і автоматика',
    groupAccount: 'Акаунт',
    syncTitle: 'Синхронізація між пристроями',
    syncSub: 'Не увімкнена — дані лише на цьому телефоні',
    groupReminders: 'Нагадування',
    reminderCharge: 'За 3 дні до списання',
    reminderPrice: 'Про зміну ціни',
    reminderUnused: 'Про невикористані підписки',
    groupGeneral: 'Основне',
    currency: 'Валюта за замовчуванням',
    theme: 'Тема',
    themeValue: 'Системна',
    language: 'Мова',
    languageValue: 'Українська',
    groupPrivacy: 'Дані та приватність',
    exportCsv: 'Експортувати дані (CSV)',
    privacyPolicy: 'Політика приватності',
    privacyPolicySub: 'Розпізнавання — тільки на пристрої',
    deleteAll: 'Видалити всі дані',
    groupSupport: 'Підтримка',
    help: 'Допомога',
    about: 'Про застосунок',
    version: 'Snapsy · версія 1.0.0',
  },
  add: {
    title: 'Нова підписка',
    scanCtaTitle: 'Швидше через фото',
    scanCtaSub: 'Відскануй чек — і не заповнюй вручну',
    merchantLabel: 'Мерчант',
    categoryLabel: 'Категорія',
    amountLabel: 'Сума',
    cycleLabel: 'Періодичність',
    firstChargeLabel: 'Перше списання',
    reminderTitle: 'Нагадати про списання',
    reminderSub: 'За 3 дні до оплати',
    submit: 'Додати підписку',
  },
  categories: {
    streaming: 'Стрімінг',
    software: 'Софт',
    fitness: 'Фітнес',
    games: 'Ігри',
    cloud: 'Хмара',
    other: 'Інше',
  },
  cycles: {
    weekly: 'Тиждень',
    monthly: 'Місяць',
    yearly: 'Рік',
    once: 'Разово',
  },
  confirm: {
    title: 'Перевір дані',
    sourceLabel: 'Джерело: чек',
    merchantLabel: 'Мерчант',
    amountLabel: 'Сума',
    periodLabel: 'Період',
    periodWarn: 'Перевір',
    nextChargeLabel: 'Наступне списання',
    save: 'Зберегти підписку',
    notASubscription: 'Це не підписка',
  },
  subscriptionDetail: {
    idPrefix: 'id: ',
    nextChargePrefix: 'Наступне списання — ',
    cancel: 'Скасувати',
    pause: 'Пауза',
    historyTitle: 'Історія платежів',
    remindersTitle: 'Нагадування',
    reminderRow: 'За 3 дні до списання',
  },
  paywall: {
    eyebrow: 'SNAPSY PRO',
    title: 'Безліміт підписок і повна автоматика',
    feature1: 'Необмежена кількість підписок',
    feature2: 'Пакетне сканування галереї',
    feature3: 'Форвард e-mail рахунків',
    feature4: 'Сповіщення про зміну ціни',
    yearlyBadge: 'Найвигідніше · −48%',
    yearlyName: 'Річний',
    yearlyPerMonth: '2,08 $ / міс',
    yearlyPrice: '24,99 $',
    yearlyPeriod: 'на рік',
    monthlyName: 'Місячний',
    monthlySub: 'Скасування будь-коли',
    monthlyPrice: '3,99 $',
    monthlyPeriod: 'на місяць',
    lifetimeLinkPrefix: 'Або купити назавжди — ',
    lifetimePrice: '59,99 $',
    startTrial: 'Почати 7-денний пробний період',
    trialNote: 'Далі 24,99 $/рік. Скасувати можна в один тап.',
    restorePurchases: 'Відновити покупки',
    terms: 'Умови',
    privacy: 'Приватність',
  },
} as const;
